### ISSUE TITLE
Choose track terms for general elections - Twitter 

### ISSUE THREAD

**Issue by mn1510** [hamemuh/UKelections2017#1]

**Comment by jcalcutt** [comment]
Here's my suggestions:
["Jeremy Corbyn",  "Corbyn", "Labour", "Lib Dem","Liberal Democrat",  
"Green Party", "Prime Minister", "UKIP", "SNP",
"Nicola Sturgeon", "Theresa May", "Conservative", "tories",
"Caroline Lucas", "Jonathan Bartley"]

**Comment by sammyjld** [comment]
Here's my suggestions (That Jordan hasnt already got)
- Labour Party
-Conservative Party
- London Election
- Vote
- Poll
- Voting
- Election 2017
- General Election
- Brexit
- Parliment
- Nick Clegg
- Candidates
- Campaign
- GE2017
- Tim Farron
- MPs
- Tories Out
- Vote SNP
- Vote2017
- GeneralElection2017
- WelshLibDems


Also are these case sensitive??
These are not my views btw! i've just observed some tweets on twitter and we can expand on these.
I.e for 'ToriesOut' also supply a 'LabourOut'

**Comment by izzy-sha-1** [comment]
- election2017
- votelabour
- votegreens
- votetory
- conservatives

and some more mildly biased ones

- toriesout
- jc4pm
- jezwecan

**Comment by mn1510** [comment]
["Theresa May", "Jeremy Corbyn", "Tim Farron", "Brexit", "Tories", "Labour", "Liberal Democrat", "Article50", "snap election", "hard brexit", "soft brexit", "market access", "negotiations", "immigration", "single market", "tax hike", "Eu hardline", "coalition government", "Tories", "SNP", "Greens", "Nicola Sturgeon", "Caroline Lucas", "Paul Nuttall"]

**Comment by jcalcutt** [comment]
[trackterms.txt](https://github.com/hamemuh/UKelections2017/files/987064/trackterms.txt)
