### ISSUE TITLE
Understand how location works in Twitter

### ISSUE THREAD

**Issue by mn1510** [hamemuh/UKelections2017#11]

**Comment by sammyjld** [comment]
Ok so what i've found so far: 
I assume we all have the same twitter scraper, with the columns 'User_location', 'Coordinates' and 'Geo'.

There are rows in which these columns actually have data (the odd few where these users have turned their locations on for tweets).

User_location is a bit odd, as some of the locations are a bit all over the place. E.g. "Caerdydd/Bath/Bristol" and "330 by way of the 440 and 419"

Where the User_location is 'Brazil', the Coordinates are {"type": "Point", "coordinates": [-3.03333, 53.4]}. This in google maps is located in the sea and comes no where near Brazil.
But on this same row, the tweet text is " Top floor where I work. Liverpool in the back looks stunning ?? #liverpool #uk #office #work… https://t.co/eU00vqV2dT ". And liverpool is no where near brazil. 
But.... under the "geo" column, the coordinates are the opposite way "{"type": "Point", "coordinates": [53.4, -3.03333]}" And this infact in google actually pinpoints to Liverpool. 

So if we are going to use location, we can only use it for a number of the tweets we have, and it seems the 'Geo' and more accurate than 'Coordinates'.
