### ISSUE TITLE
First sentiment outputs for Sprint 1

### ISSUE THREAD

**Issue by mn1510** [hamemuh/UKelections2017#9]

**Comment by mn1510** [comment]
1. Python code adjustment
2. Sentiment analysis method
3. Understanding python code location

**Comment by jcalcutt** [comment]
**For 'practice' data:**
mongo IP: 10.50.0.128:27017
twitterdb -> testfilter3

**Comment by mn1510** [comment]
Deliverables for Week 1:
Documentation write up for all workpoints assigned to everyone
1. Mohsin - Initial Sentiment line graph per bin on plotly using 3 days of streaming data, Sentiment methodology, project plan, compile documentation
2. Sammy - Location to determine swing regions (method)
3. Project plan write up - Mohsin/Muhammed
4. Jordan - Write up justification of key term choices/binning strategy + code snapshots that are explained
5. Izzy  - Sentiment analysis method, github investigation
6. Muhammed - Feeding in database into python dataframe + plotting 
- Would like this as soon as possible by the weekend
Friday Meeting discussion:
In order of priority:
1. Agreement on Sentiment output measure - All of us
2. External data sourcing strategy - All of us
3..  Bubble plots research - Muhammed/Mohsin/Jordan 
4.  Using Jordans active database, plot sentiment graph for tweets text (Mohsin), plot hashtag sentiment graph (Muhammed)
5. Plan for Sprint 2
